Breaking: update theme bg image selector (fixes #59)
cgkineo/adapt-visua11y pull request #61
Opened 2022-12-15 14:25 UTC by kirsty-hames

'no background images' no longer hides Vanilla and Boxmenu background images since the following amends were made to apply the `background-image` to it's own div.

https://github.com/adaptlearning/adapt-contrib-vanilla/pull/334
https://github.com/adaptlearning/adapt-contrib-boxMenu/pull/119

[modifiers.less](https://github.com/cgkineo/adapt-visua11y/blob/e89f13ec784c1a997f9eec8a9646849f3f62cc8e/less/modifiers.less#L69) just needs updating to target the .background element instead.

2023-01-04 11:11 UTC, StuartNicholls approved these changes

2023-01-04 12:17 UTC, joe-allen-89 approved these changes

2023-01-05 16:15 UTC, guywillis approved these changes
👀

2023-01-05 17:13 UTC, StuartNicholls reviewed
@kirsty-hames lines 13 & 33 also need updating I think so they should read:

  .has-bg-image > .background

2023-01-05 17:15 UTC, StuartNicholls requested changes
See above

2023-01-09 14:11 UTC, merged